# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    empty_statements: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_init_to_null: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    constant_identifier_names: true
    lines_longer_than_80_chars: true
    no_literal_bool_comparisons: true
    prefer_const_constructors: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_parenthesis: true
    use_colored_box: true
    use_decorated_box: true
    void_checks: true
